server:
  port: 8081

spring:
  profiles:
    default: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/home-hub
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true